### ISSUE TITLE
Think the patch needs a rebase?  Maybe I'm doing something catastrophically wrong, too.  

### ISSUE THREAD

**Issue by faddat** [mytechpg/mptcp_openwrt#1]
Well, that's it, sorry nothing more :).  

Update:  Not really true though:  I'm reproducing the issue now so I can show you
[build err.txt](https://github.com/mytechpg/mptcp_openwrt/files/180570/build.err.txt)

 the terminal output from the failure.  Trying to build for AMD64.  
[build err.txt](https://github.com/mytechpg/mptcp_openwrt/files/180571/build.err.txt)

**Comment by mytechpg** [comment]
Hello,

Sorry, I have just read your full comment on git hub.
Did you solve your problem?

which kernel version are you using?

andrea

2016-03-18 12:40 GMT+01:00 Jacob Gadikian notifications@github.com:

**Comment by mytechpg** [comment]
I have updated the patch for kernel 3.18.29 and it solves also your problem
Regards

andrea

**Comment by faddat** [comment]
oh-- awesome!

Thank you @mytechpg
